runtime: nodejs16 # or another supported version

instance_class: F1

handlers:
  - url: /
    static_files: storybook-static/index.html
    upload: storybook-static/index.html

  - url: /(.*)
    static_files: storybook-static/\1
    upload: storybook-static/(.*)
